lang: ruby
rvm:
- 2.2
before_install:
- gem install asciidoctor
- gem install --pre asciidoctor-pdf
before_script:
- chmod +x ".travis/build_doc.sh"
script:
- ".travis/build_doc.sh"
deploy:
  provider: releases
  api_key:
    secure: CEPEljvg7UsRQ06bKfDoUJOCmSZYFGN+OZFimZ/J2s2jwVKCX8V7eo3xO+VflXJ8jJpVJfTnq96zda/DKeNQm0naBREDswQiulGocikDQ5LzrhNC617rdryBp7/CGBT6EZoOwCUMqjtG5UYewE59ukyQT+ZLgJczG3lzdtJg2VkGJuLxVQT9A6AyGMu2bALEWb+1dxt0Yq0UnLAPW8hB0jUkTQ1PC0hyPxXRpKcqKAXo89MYFxTTAojmJM9n69Vtdp5SJhAtH7t0s8XbOtYm5XIZNtrfF49wvkmunyVDGBn1iDSwZeLcFOTQaaS7XJSEVhzyXmcGv04laZ7UQtn876mvXhqZ+Ku+R9rL1u1gtbizgkg1E4AOnXHVbsetvm2WQEW3Di6Vf/LW3/0cafm6jwWG9x6OC+c+Htwjx12nJXpnr8qH6fVWkkoWG3K8cKndRCpTLAlxHJGUcOQ5rUuflyrJft1SPENc3nc0IRYyi09UEHBuNaPuTTTW7XTqdLfBPcSAKlfnsG6FmgmBqcwZjnOmHVEmorbo7IGVJzMDE9/h0YOXHzNMRrZmNA5uuJQfpwI9gt0oHXP2Y7y6WtdRJfoJIe+HeBgpbwutLBhZATZZoLmYNU8gMGjp7MeQls+L1nTJDkVPkw3ej6nwS0lni+TNWmNdFEaN2FKjQy8OLoA=
  file: ./doc/pdf/Dokumentation.zip
  skip_cleanup: true
  on:
    repo: fried-ice/Medida_2016_11
    tags: true
    all_branches: true
