= Spielidee 2 - {game_title}
include::fragments/_head.adoc[]
:changedate: 09.04.2016

== Allgemeines

*Gruppe:*:: {group_id}

*Gruppenname:*:: {group_title}

*Bezeichnung:*:: {game_title}

*Zielgruppe:*:: Menschen mit wenig Erfahrung im Umgang mit Computern

== Inhalt

Das Lernspiel {game_title} hat es sich zur Aufgabe gemacht, älteren Menschen ohne weitere entsprechende Vorkenntnisse den Umgang mit dem Computer näherzubringen.
Dazu sollen veranschaulichende Grafiken und Texte genutzt werden und in eine ansprechende Spielumgebung eingebettet werden, welche wie unten beschrieben aussehen könnte.

== Art der Umsetzung

Denkbar wären an dieser Stelle verdeutlichende Screenshots aus gängigen Programmen, wie E-Mail Clients, Webbrowser und Officeanwendungen, bei denen der Spieler auf die richtige (animierte) Schaltfläche drücken muss oder Multiple Choice Fragen beantwortet um den Spielverlauf voranzutreiben.
Einige gängige Sicherheitstipps für den Alltag könnten ebenfalls aufgenommen werden, wie beispielsweise die Simulation einer Phishing-Attacke.

Bei falschen Antworten oder Unkenntnis des Spielers werden die Lösungen temporär eingeblendet und müssen/können später erneut beantwortet werden.

Nachdem der Spieler alle Aufgaben richtig gelöst hat erwartet ihn ein Gewinnbildschirm und die Option, sein neu erworbenes "Fachwissen" in Form einer Urkunde auszudrucken.

Programmierumgebung und -sprache sind zum aktuellen Zeitpunkt noch nicht festgelegt.
